# Generated by Django 3.1.5 on 2021-01-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('father_name', models.CharField(max_length=60)),
                ('cnic', models.CharField(max_length=60)),
                ('designation', models.CharField(max_length=60)),
                ('district', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=60)),
                ('imei', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='geolog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=60)),
                ('imei', models.CharField(max_length=60)),
                ('lat', models.CharField(max_length=60)),
                ('long', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date1', models.CharField(max_length=60)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.user')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(max_length=60)),
                ('imei', models.CharField(max_length=60)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lat', models.CharField(max_length=60)),
                ('long', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=60)),
                ('date1', models.CharField(max_length=60)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.user')),
            ],
        ),
    ]
