# Generated by Django 3.1.5 on 2021-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joining_date',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
    ]
