# Generated by Django 3.1.5 on 2021-01-28 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0004_auto_20210128_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolog',
            old_name='long',
            new_name='lon',
        ),
    ]
