# Generated by Django 3.1.5 on 2021-01-28 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0005_auto_20210128_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolog',
            old_name='lon',
            new_name='long',
        ),
    ]
